import type { Dish } from "./types";

/**
 * Seed catalogue. This is the layer you replace with a real feed later:
 * a partner API, a per-city curated sheet, or your own crawl.
 * Nothing above this file knows where the dishes came from.
 *
 * Vector values are 0 to 1. Keep them honest, the whole engine rests on them.
 */
export const DISHES: Dish[] = [
  {
    id: "khichdi",
    name: "Moong dal khichdi",
    cuisine: "Home-style Indian",
    searchTerm: "khichdi",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 30,
    priceBand: 1,
    slots: ["lunch", "dinner", "latenight"],
    zomatoDish: "dal-khichdi",
    vector: { comfort: 0.98, indulgence: 0.15, heat: 0.1, lightness: 0.9, novelty: 0.05, sweetness: 0.05 },
    note: "The one food that asks nothing of you.",
  },
  {
    id: "curd-rice",
    name: "Curd rice with pickle",
    cuisine: "South Indian",
    searchTerm: "curd rice",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 25,
    priceBand: 1,
    slots: ["lunch", "dinner", "latenight"],
    vector: { comfort: 0.95, indulgence: 0.1, heat: 0.15, lightness: 0.95, novelty: 0.05, sweetness: 0.05 },
    note: "Cools everything down, including you.",
  },
  {
    id: "rasam-rice",
    name: "Rasam and rice",
    cuisine: "South Indian",
    searchTerm: "rasam rice",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 30,
    priceBand: 1,
    slots: ["lunch", "dinner"],
    vector: { comfort: 0.9, indulgence: 0.15, heat: 0.45, lightness: 0.85, novelty: 0.1, sweetness: 0.05 },
    note: "Warm, sour, thin enough to drink when nothing else appeals.",
  },
  {
    id: "hyd-biryani",
    name: "Hyderabadi chicken dum biryani",
    cuisine: "Hyderabadi",
    searchTerm: "hyderabadi chicken biryani",
    veg: false,
    containsEgg: true,
    portion: "feast",
    eta: 45,
    priceBand: 2,
    slots: ["lunch", "dinner", "latenight"],
    zomatoDish: "chicken-biryani",
    vector: { comfort: 0.85, indulgence: 0.8, heat: 0.7, lightness: 0.2, novelty: 0.1, sweetness: 0.1 },
    note: "The default celebration, and it earns it.",
  },
  {
    id: "veg-biryani",
    name: "Vegetable dum biryani",
    cuisine: "Hyderabadi",
    searchTerm: "veg dum biryani",
    veg: true,
    containsEgg: false,
    portion: "feast",
    eta: 40,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    zomatoDish: "biryani",
    vector: { comfort: 0.75, indulgence: 0.65, heat: 0.6, lightness: 0.3, novelty: 0.15, sweetness: 0.1 },
    note: "Same ceremony, lighter landing.",
  },
  {
    id: "butter-chicken",
    name: "Butter chicken and naan",
    cuisine: "North Indian",
    searchTerm: "butter chicken naan",
    veg: false,
    containsEgg: false,
    portion: "meal",
    eta: 40,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    zomatoDish: "butter-chicken",
    vector: { comfort: 0.85, indulgence: 0.9, heat: 0.25, lightness: 0.15, novelty: 0.05, sweetness: 0.35 },
    note: "Sweet, heavy, and completely unembarrassed about it.",
  },
  {
    id: "dal-khichdi-ghee",
    name: "Dal tadka, jeera rice, ghee",
    cuisine: "North Indian",
    searchTerm: "dal tadka jeera rice",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 35,
    priceBand: 1,
    slots: ["lunch", "dinner"],
    vector: { comfort: 0.9, indulgence: 0.4, heat: 0.3, lightness: 0.65, novelty: 0.05, sweetness: 0.1 },
    note: "The meal you would cook if you had the energy to cook.",
  },
  {
    id: "paneer-butter-masala",
    name: "Paneer butter masala with roti",
    cuisine: "North Indian",
    searchTerm: "paneer butter masala",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 40,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    zomatoDish: "paneer-butter-masala",
    vector: { comfort: 0.8, indulgence: 0.85, heat: 0.3, lightness: 0.2, novelty: 0.05, sweetness: 0.35 },
    note: "Rich, safe, hard to get wrong.",
  },
  {
    id: "chicken-65",
    name: "Chicken 65",
    cuisine: "Hyderabadi",
    searchTerm: "chicken 65",
    veg: false,
    containsEgg: true,
    portion: "snack",
    eta: 30,
    priceBand: 2,
    slots: ["snack", "dinner", "latenight"],
    zomatoDish: "chicken",
    vector: { comfort: 0.6, indulgence: 0.85, heat: 0.85, lightness: 0.15, novelty: 0.2, sweetness: 0.05 },
    note: "Loud, red, and best eaten standing up.",
  },
  {
    id: "andhra-chicken-curry",
    name: "Andhra chicken curry with rice",
    cuisine: "Andhra",
    searchTerm: "andhra chicken curry",
    veg: false,
    containsEgg: false,
    portion: "meal",
    eta: 45,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    zomatoDish: "chicken",
    vector: { comfort: 0.7, indulgence: 0.6, heat: 0.95, lightness: 0.3, novelty: 0.25, sweetness: 0.05 },
    note: "Heat as a personality, not a garnish.",
  },
  {
    id: "gongura-mutton",
    name: "Gongura mutton",
    cuisine: "Andhra",
    searchTerm: "gongura mutton",
    veg: false,
    containsEgg: false,
    portion: "feast",
    eta: 50,
    priceBand: 3,
    slots: ["lunch", "dinner"],
    zomatoDish: "mutton",
    vector: { comfort: 0.55, indulgence: 0.8, heat: 0.9, lightness: 0.2, novelty: 0.55, sweetness: 0.05 },
    note: "Sour, fierce, worth the wait and the price.",
  },
  {
    id: "masala-dosa",
    name: "Masala dosa",
    cuisine: "South Indian",
    searchTerm: "masala dosa",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 30,
    priceBand: 1,
    slots: ["breakfast", "snack", "dinner"],
    zomatoDish: "masala-dosa",
    vector: { comfort: 0.85, indulgence: 0.5, heat: 0.3, lightness: 0.55, novelty: 0.05, sweetness: 0.1 },
    note: "Works at any hour, which is the whole point of it.",
  },
  {
    id: "idli-sambar",
    name: "Idli, sambar, chutney",
    cuisine: "South Indian",
    searchTerm: "idli sambar",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 25,
    priceBand: 1,
    slots: ["breakfast", "snack", "latenight"],
    zomatoDish: "idli",
    vector: { comfort: 0.9, indulgence: 0.1, heat: 0.25, lightness: 0.95, novelty: 0.05, sweetness: 0.05 },
    note: "Soft, steamed, no argument.",
  },
  {
    id: "pesarattu",
    name: "Pesarattu with upma",
    cuisine: "Andhra",
    searchTerm: "pesarattu upma",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 30,
    priceBand: 1,
    slots: ["breakfast", "snack"],
    vector: { comfort: 0.7, indulgence: 0.25, heat: 0.4, lightness: 0.7, novelty: 0.4, sweetness: 0.05 },
    note: "Green, protein-heavy, sharper than it looks.",
  },
  {
    id: "poha",
    name: "Poha",
    cuisine: "Home-style Indian",
    searchTerm: "poha",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 25,
    priceBand: 1,
    slots: ["breakfast", "snack"],
    localTo: ["indore", "bhopal"],
    vector: { comfort: 0.85, indulgence: 0.15, heat: 0.2, lightness: 0.9, novelty: 0.1, sweetness: 0.15 },
    note: "Light enough that you will not regret it at 11am.",
  },
  {
    id: "irani-chai-osmania",
    name: "Irani chai and Osmania biscuits",
    cuisine: "Hyderabadi",
    searchTerm: "irani chai osmania biscuit",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 20,
    priceBand: 1,
    slots: ["breakfast", "snack", "latenight"],
    vector: { comfort: 0.9, indulgence: 0.4, heat: 0.05, lightness: 0.7, novelty: 0.15, sweetness: 0.6 },
    note: "Not a meal. Sometimes not a meal is the answer.",
  },
  {
    id: "samosa-chai",
    name: "Samosa with chai",
    cuisine: "Street food",
    searchTerm: "samosa",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 25,
    priceBand: 1,
    slots: ["snack", "latenight"],
    zomatoDish: "samosa",
    vector: { comfort: 0.8, indulgence: 0.7, heat: 0.35, lightness: 0.3, novelty: 0.05, sweetness: 0.2 },
    note: "Fried carbohydrate, hot tea, four in the evening.",
  },
  {
    id: "pav-bhaji",
    name: "Pav bhaji",
    cuisine: "Street food",
    searchTerm: "pav bhaji",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 30,
    priceBand: 1,
    slots: ["snack", "dinner", "latenight"],
    localTo: ["mumbai", "pune"],
    zomatoDish: "pav-bhaji",
    vector: { comfort: 0.85, indulgence: 0.85, heat: 0.45, lightness: 0.2, novelty: 0.1, sweetness: 0.15 },
    note: "Butter doing most of the emotional work.",
  },
  {
    id: "vada-pav",
    name: "Vada pav",
    cuisine: "Street food",
    searchTerm: "vada pav",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 20,
    priceBand: 1,
    slots: ["snack", "latenight"],
    localTo: ["mumbai", "pune"],
    zomatoDish: "vada-pav",
    vector: { comfort: 0.75, indulgence: 0.75, heat: 0.6, lightness: 0.25, novelty: 0.15, sweetness: 0.1 },
    note: "Cheap, fast, aggressively satisfying.",
  },
  {
    id: "pani-puri",
    name: "Pani puri",
    cuisine: "Street food",
    searchTerm: "pani puri",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 25,
    priceBand: 1,
    slots: ["snack"],
    vector: { comfort: 0.6, indulgence: 0.4, heat: 0.6, lightness: 0.7, novelty: 0.3, sweetness: 0.35 },
    note: "Sharp and cold, resets a dull afternoon.",
  },
  {
    id: "chole-bhature",
    name: "Chole bhature",
    cuisine: "North Indian",
    searchTerm: "chole bhature",
    veg: true,
    containsEgg: false,
    portion: "feast",
    eta: 35,
    priceBand: 1,
    slots: ["breakfast", "lunch"],
    zomatoDish: "chole-bhature",
    vector: { comfort: 0.7, indulgence: 0.95, heat: 0.55, lightness: 0.05, novelty: 0.15, sweetness: 0.1 },
    note: "Commits you to a slow afternoon. Plan accordingly.",
  },
  {
    id: "rajma-chawal",
    name: "Rajma chawal",
    cuisine: "North Indian",
    searchTerm: "rajma chawal",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 35,
    priceBand: 1,
    slots: ["lunch", "dinner"],
    vector: { comfort: 0.95, indulgence: 0.4, heat: 0.3, lightness: 0.5, novelty: 0.05, sweetness: 0.1 },
    note: "Nostalgia in a bowl, and genuinely filling.",
  },
  {
    id: "shawarma",
    name: "Chicken shawarma roll",
    cuisine: "Middle Eastern",
    searchTerm: "chicken shawarma",
    veg: false,
    containsEgg: true,
    portion: "meal",
    eta: 30,
    priceBand: 1,
    slots: ["snack", "dinner", "latenight"],
    localTo: ["kochi", "trivandrum", "hyderabad"],
    zomatoDish: "chicken-shawarma",
    vector: { comfort: 0.6, indulgence: 0.7, heat: 0.4, lightness: 0.4, novelty: 0.3, sweetness: 0.1 },
    note: "Portable, garlicky, hard to argue with at midnight.",
  },
  {
    id: "hummus-pita",
    name: "Hummus, falafel and pita",
    cuisine: "Middle Eastern",
    searchTerm: "hummus falafel pita",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 40,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    vector: { comfort: 0.5, indulgence: 0.45, heat: 0.15, lightness: 0.7, novelty: 0.5, sweetness: 0.1 },
    note: "Light but not sad, which is a narrow target.",
  },
  {
    id: "margherita",
    name: "Margherita pizza",
    cuisine: "Italian",
    searchTerm: "margherita pizza",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 35,
    priceBand: 2,
    slots: ["lunch", "dinner", "latenight"],
    zomatoDish: "pizza",
    vector: { comfort: 0.85, indulgence: 0.8, heat: 0.05, lightness: 0.25, novelty: 0.05, sweetness: 0.2 },
    note: "The dish you order when you do not want to decide.",
  },
  {
    id: "arrabiata",
    name: "Penne arrabiata",
    cuisine: "Italian",
    searchTerm: "penne arrabiata",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 35,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    vector: { comfort: 0.65, indulgence: 0.55, heat: 0.6, lightness: 0.45, novelty: 0.25, sweetness: 0.2 },
    note: "Enough chilli to feel like a choice.",
  },
  {
    id: "alfredo",
    name: "Alfredo pasta",
    cuisine: "Italian",
    searchTerm: "alfredo pasta",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 35,
    priceBand: 2,
    slots: ["lunch", "dinner", "latenight"],
    zomatoDish: "pasta",
    vector: { comfort: 0.85, indulgence: 0.95, heat: 0.05, lightness: 0.1, novelty: 0.1, sweetness: 0.2 },
    note: "Cream as a coping mechanism.",
  },
  {
    id: "ramen",
    name: "Shoyu ramen",
    cuisine: "Japanese",
    searchTerm: "ramen",
    veg: false,
    containsEgg: true,
    portion: "meal",
    eta: 45,
    priceBand: 3,
    slots: ["lunch", "dinner", "latenight"],
    zomatoDish: "ramen",
    vector: { comfort: 0.9, indulgence: 0.6, heat: 0.25, lightness: 0.5, novelty: 0.55, sweetness: 0.1 },
    note: "Hot broth fixes more than it should.",
  },
  {
    id: "sushi",
    name: "Assorted sushi",
    cuisine: "Japanese",
    searchTerm: "sushi",
    veg: false,
    containsEgg: false,
    portion: "meal",
    eta: 50,
    priceBand: 3,
    slots: ["lunch", "dinner"],
    zomatoDish: "sushi",
    vector: { comfort: 0.3, indulgence: 0.5, heat: 0.15, lightness: 0.85, novelty: 0.8, sweetness: 0.15 },
    note: "Precise, cold, deliberately unlike everything else here.",
  },
  {
    id: "pad-thai",
    name: "Pad thai",
    cuisine: "Thai",
    searchTerm: "pad thai",
    veg: false,
    containsEgg: true,
    portion: "meal",
    eta: 40,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    vector: { comfort: 0.55, indulgence: 0.6, heat: 0.4, lightness: 0.45, novelty: 0.6, sweetness: 0.5 },
    note: "Sweet, sour and salty at once, which is the appeal.",
  },
  {
    id: "thai-green-curry",
    name: "Thai green curry with rice",
    cuisine: "Thai",
    searchTerm: "thai green curry",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 45,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    vector: { comfort: 0.6, indulgence: 0.6, heat: 0.65, lightness: 0.5, novelty: 0.6, sweetness: 0.25 },
    note: "Coconut softens the heat without removing it.",
  },
  {
    id: "khao-suey",
    name: "Khow suey",
    cuisine: "Burmese",
    searchTerm: "khow suey",
    veg: true,
    containsEgg: true,
    portion: "meal",
    eta: 45,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    localTo: ["kolkata"],
    vector: { comfort: 0.7, indulgence: 0.6, heat: 0.45, lightness: 0.5, novelty: 0.8, sweetness: 0.2 },
    note: "Half the pleasure is assembling the toppings yourself.",
  },
  {
    id: "momos",
    name: "Steamed chicken momos",
    cuisine: "Tibetan",
    searchTerm: "chicken momos",
    veg: false,
    containsEgg: false,
    portion: "snack",
    eta: 30,
    priceBand: 1,
    slots: ["snack", "dinner", "latenight"],
    localTo: ["ncr", "kolkata", "guwahati"],
    zomatoDish: "momos",
    vector: { comfort: 0.7, indulgence: 0.35, heat: 0.5, lightness: 0.7, novelty: 0.3, sweetness: 0.05 },
    note: "Light, hot, and the chutney does the rest.",
  },
  {
    id: "veg-momos",
    name: "Steamed veg momos",
    cuisine: "Tibetan",
    searchTerm: "veg momos",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 30,
    priceBand: 1,
    slots: ["snack", "dinner", "latenight"],
    localTo: ["ncr", "kolkata", "guwahati"],
    zomatoDish: "momos",
    vector: { comfort: 0.7, indulgence: 0.3, heat: 0.45, lightness: 0.75, novelty: 0.25, sweetness: 0.05 },
    note: "A snack that does not feel like a compromise.",
  },
  {
    id: "hakka-noodles",
    name: "Hakka noodles",
    cuisine: "Indo-Chinese",
    searchTerm: "hakka noodles",
    veg: true,
    containsEgg: true,
    portion: "meal",
    eta: 30,
    priceBand: 1,
    slots: ["snack", "dinner", "latenight"],
    zomatoDish: "noodles",
    vector: { comfort: 0.8, indulgence: 0.6, heat: 0.5, lightness: 0.4, novelty: 0.1, sweetness: 0.15 },
    note: "Reliable, greasy, arrives fast.",
  },
  {
    id: "chilli-chicken",
    name: "Chilli chicken",
    cuisine: "Indo-Chinese",
    searchTerm: "chilli chicken",
    veg: false,
    containsEgg: true,
    portion: "snack",
    eta: 35,
    priceBand: 2,
    slots: ["snack", "dinner", "latenight"],
    zomatoDish: "chilli-chicken",
    vector: { comfort: 0.65, indulgence: 0.85, heat: 0.8, lightness: 0.2, novelty: 0.15, sweetness: 0.3 },
    note: "Sticky, sharp, made for sharing badly.",
  },
  {
    id: "burger",
    name: "Crispy chicken burger and fries",
    cuisine: "American",
    searchTerm: "chicken burger",
    veg: false,
    containsEgg: true,
    portion: "meal",
    eta: 30,
    priceBand: 2,
    slots: ["lunch", "snack", "dinner", "latenight"],
    zomatoDish: "burger",
    vector: { comfort: 0.8, indulgence: 0.95, heat: 0.3, lightness: 0.1, novelty: 0.05, sweetness: 0.25 },
    note: "No pretence, no surprises, immediate payoff.",
  },
  {
    id: "grilled-chicken-bowl",
    name: "Grilled chicken and quinoa bowl",
    cuisine: "Salads and bowls",
    searchTerm: "grilled chicken bowl",
    veg: false,
    containsEgg: false,
    portion: "meal",
    eta: 35,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    zomatoDish: "chicken",
    vector: { comfort: 0.35, indulgence: 0.2, heat: 0.2, lightness: 0.9, novelty: 0.35, sweetness: 0.1 },
    note: "The one that leaves you able to work afterwards.",
  },
  {
    id: "greek-salad",
    name: "Greek salad",
    cuisine: "Salads and bowls",
    searchTerm: "greek salad",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 30,
    priceBand: 2,
    slots: ["lunch", "dinner"],
    zomatoDish: "salad",
    vector: { comfort: 0.3, indulgence: 0.25, heat: 0.05, lightness: 0.95, novelty: 0.4, sweetness: 0.15 },
    note: "Cold and salty, good when the day has been heavy.",
  },
  {
    id: "egg-bhurji-pav",
    name: "Egg bhurji with pav",
    cuisine: "Street food",
    searchTerm: "egg bhurji pav",
    veg: false,
    containsEgg: true,
    portion: "meal",
    eta: 25,
    priceBand: 1,
    slots: ["breakfast", "dinner", "latenight"],
    zomatoDish: "egg",
    vector: { comfort: 0.85, indulgence: 0.55, heat: 0.5, lightness: 0.5, novelty: 0.15, sweetness: 0.05 },
    note: "Protein and butter at any hour of the night.",
  },
  {
    id: "haleem",
    name: "Haleem",
    cuisine: "Hyderabadi",
    searchTerm: "haleem",
    veg: false,
    containsEgg: false,
    portion: "meal",
    eta: 40,
    priceBand: 2,
    slots: ["dinner", "latenight"],
    vector: { comfort: 0.85, indulgence: 0.85, heat: 0.4, lightness: 0.15, novelty: 0.35, sweetness: 0.05 },
    note: "Dense, slow-cooked, closer to a hug than a meal.",
  },
  {
    id: "tandoori-chicken",
    name: "Tandoori chicken",
    cuisine: "North Indian",
    searchTerm: "tandoori chicken",
    veg: false,
    containsEgg: false,
    portion: "feast",
    eta: 45,
    priceBand: 2,
    slots: ["dinner"],
    zomatoDish: "tandoori-chicken",
    vector: { comfort: 0.6, indulgence: 0.6, heat: 0.6, lightness: 0.5, novelty: 0.15, sweetness: 0.1 },
    note: "Smoky, shareable, meant for a table with people at it.",
  },
  {
    id: "gulab-jamun",
    name: "Gulab jamun",
    cuisine: "Indian sweets",
    searchTerm: "gulab jamun",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 25,
    priceBand: 1,
    slots: ["snack", "dinner", "latenight"],
    zomatoDish: "gulab-jamun",
    vector: { comfort: 0.9, indulgence: 0.9, heat: 0, lightness: 0.2, novelty: 0.05, sweetness: 1 },
    note: "Skip straight to the end of the meal.",
  },
  {
    id: "double-ka-meetha",
    name: "Double ka meetha",
    cuisine: "Hyderabadi",
    searchTerm: "double ka meetha",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 30,
    priceBand: 1,
    slots: ["snack", "dinner"],
    vector: { comfort: 0.85, indulgence: 0.9, heat: 0, lightness: 0.15, novelty: 0.35, sweetness: 0.95 },
    note: "Bread, ghee and sugar, which is all a celebration needs.",
  },
  {
    id: "brownie-icecream",
    name: "Warm brownie with ice cream",
    cuisine: "Desserts",
    searchTerm: "brownie ice cream",
    veg: true,
    containsEgg: true,
    portion: "snack",
    eta: 30,
    priceBand: 2,
    slots: ["snack", "dinner", "latenight"],
    zomatoDish: "ice-cream",
    vector: { comfort: 0.9, indulgence: 0.95, heat: 0, lightness: 0.15, novelty: 0.1, sweetness: 1 },
    note: "For the nights that are not about nutrition.",
  },
  {
    id: "filter-coffee",
    name: "Filter coffee and a vada",
    cuisine: "South Indian",
    searchTerm: "filter coffee vada",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 20,
    priceBand: 1,
    slots: ["breakfast", "snack"],
    zomatoDish: "coffee",
    vector: { comfort: 0.85, indulgence: 0.5, heat: 0.3, lightness: 0.6, novelty: 0.1, sweetness: 0.4 },
    note: "Caffeine with something to chew on.",
  },
  // Vrat food. India's fasting calendar is not an edge case: navratri,
  // ekadashi, monday fasts and ramadan recur constantly, and on a vrat day the
  // rest of this catalogue is simply unorderable. Ingredients follow what the
  // observance actually permits - sabudana, kuttu and singhara flour, fruit,
  // dairy, rock salt - rather than being ordinary dishes relabelled.
  {
    id: "sabudana-khichdi",
    name: "Sabudana khichdi",
    cuisine: "Home-style Indian",
    searchTerm: "sabudana khichdi",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 30,
    priceBand: 1,
    slots: ["breakfast", "lunch", "snack", "dinner"],
    fastingSafe: true,
    zomatoDish: "sabudana-khichdi",
    vector: { comfort: 0.8, indulgence: 0.5, heat: 0.3, lightness: 0.5, novelty: 0.15, sweetness: 0.1 },
    note: "Peanut, potato and sago, the dish that carries every fast.",
  },
  {
    id: "kuttu-puri",
    name: "Kuttu ki puri with aloo",
    cuisine: "North Indian",
    searchTerm: "kuttu puri",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 35,
    priceBand: 1,
    slots: ["lunch", "dinner"],
    fastingSafe: true,
    vector: { comfort: 0.8, indulgence: 0.65, heat: 0.35, lightness: 0.3, novelty: 0.2, sweetness: 0.05 },
    note: "Buckwheat flour, fried, and worth the wait until evening.",
  },
  {
    id: "vrat-aloo",
    name: "Vrat wale aloo",
    cuisine: "North Indian",
    searchTerm: "vrat wale aloo",
    veg: true,
    containsEgg: false,
    portion: "meal",
    eta: 30,
    priceBand: 1,
    slots: ["lunch", "dinner"],
    fastingSafe: true,
    vector: { comfort: 0.85, indulgence: 0.45, heat: 0.4, lightness: 0.45, novelty: 0.1, sweetness: 0.05 },
    note: "Potatoes, rock salt, green chilli. Nothing else, and nothing missing.",
  },
  {
    id: "singhare-halwa",
    name: "Singhare ka halwa",
    cuisine: "Indian sweets",
    searchTerm: "singhare ka halwa",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 30,
    priceBand: 1,
    slots: ["snack", "dinner", "latenight"],
    fastingSafe: true,
    vector: { comfort: 0.85, indulgence: 0.8, heat: 0.0, lightness: 0.25, novelty: 0.25, sweetness: 0.9 },
    note: "Water chestnut flour and ghee, which is to say, ghee.",
  },
  {
    id: "fruit-dahi",
    name: "Fruit and dahi bowl",
    cuisine: "Home-style Indian",
    searchTerm: "fruit curd bowl",
    veg: true,
    containsEgg: false,
    portion: "snack",
    eta: 20,
    priceBand: 1,
    slots: ["breakfast", "snack", "latenight"],
    fastingSafe: true,
    zomatoDish: "fruit-bowl",
    vector: { comfort: 0.6, indulgence: 0.15, heat: 0.0, lightness: 0.95, novelty: 0.1, sweetness: 0.45 },
    note: "What a fast actually feels like breaking on.",
  },
];
