-- Moodbite: let the click stream include people who never signed in.
--
-- Two separate things were blocked by requiring an account, and they want
-- different answers.
--
-- THE AGGREGATE SIGNAL belongs in this table. dish_signals() learns from what
-- people pick, and until now it learned only from the small minority who had
-- an account - which is both thin and biased toward the already-committed.
-- Anonymous rows fix that, and they are written here.
--
-- PERSONAL HISTORY DELIBERATELY DOES NOT. The fatigue term needs to know what
-- YOU were shown last week, and the obvious design - store it against the
-- device id and read it back - would make that id a bearer token: anyone
-- holding it could read what a device had been shown. It is low-harm data and
-- it is still not ours to expose. So a signed-out reader's history stays on
-- their own device in localStorage and is sent with the request. Nothing to
-- read back, nothing to leak, and a client that lies only misleads itself.
--
-- WHAT THIS OPENS. Anyone holding the public anon key can now write events, so
-- the learned signal can be stuffed. That is bounded rather than prevented:
-- dish_signals is clamped to +/-0.075 of score, about what an exact portion
-- match is worth, and position debiasing means fake clicks must be accompanied
-- by fake impressions at plausible ranks to move anything at all. The exposure
-- is a nudge, not a takeover. It is written down here so that if the clamp is
-- ever raised, this is raised with it.
--
-- Run after 0017_dish_signals_prior.sql.

alter table public.recommendation_events alter column user_id drop not null;

alter table public.recommendation_events
  add column if not exists device_id text;

comment on column public.recommendation_events.device_id is
  'An opaque id generated by the browser and kept in localStorage. Not an identity, not linked to a person, and never used to read anything back - only to group a session''s events for aggregate counting.';

-- Every row is attributable to exactly one of the two, never neither.
alter table public.recommendation_events
  drop constraint if exists recommendation_events_has_author;
alter table public.recommendation_events
  add constraint recommendation_events_has_author
  check (user_id is not null or device_id is not null);

create index if not exists recommendation_events_device_idx
  on public.recommendation_events (device_id, created_at desc);

-- Signed out you may write rows that belong to no account. You may not write a
-- row claiming to be somebody, which is what the null check enforces.
drop policy if exists "anonymous devices may log" on public.recommendation_events;
create policy "anonymous devices may log"
  on public.recommendation_events for insert
  to anon
  with check (user_id is null and device_id is not null);

-- And no read policy for anon is added, deliberately. Anonymous rows are
-- write-only from the outside: they exist to be counted in aggregate by
-- dish_signals(), which is security definer and returns per-dish totals.
